name : Push-to-EC2


on : push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
        - name: Deploy to my EC2 instance
          uses: easingthemes/ssh-deploy@v2.1.5
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEYS }}
            SOURCE: "./"
            REMOTE_HOSTS: ${{ secrets.REMOTE_HOST }}
            REMOTE_HOSTS: ${{ secrets.REMOTE_HOST }}
            TARGET:"/home/ec2-user/"
            -name: Install Dependencies
            run: pip3 install -r requirements.txt
            
            
            
